### ISSUE TITLE
Clicking back to window causes timer to drop sharply

### ISSUE THREAD

**Issue by fortisconsulting** [adrian-miasik/unity-pomodoro#71] opened 2022-04-14 13:07 UTC
# User Bug Report

## Description
> The timer drops sharply in time remaining when I click away from the window and come back.

## Reproduction Steps
> 1. Start the timer.
> 2. Navigate away from the Unity Pomodoro app window (by clicking on another window).
> 3. Return to the Unity Pomodoro app window (by clicking anywhere on the Unity Pom. window).
> 4. The time remaining drops sharply, by a factor of roughly 50% of how long it's been since I was last at the window. 

For example, if I start the timer at 25:00, then navigate away at 24:00, then return at 22:00, then the time remaining drops to 21:00. 

## Impacted Version(s)
> - Version: 2.1.0

## Impacted Platform(s)
> - Windows 11

## Expected Behaviour
> - In the example above, it ought to simply continue counting down from 22:00 when I come back to Unity Window.

## Screenshots
> Screen-capture via zoom, saved to personal onedrive:  https://1drv.ms/v/s!AmlLolYckglnhKUrtzBvKz1xliE5oA?e=IBNab4

## Additional Context/Comments
> - Love the app! Would greatly appreciate seeing it fixed!

**Comment by adrian-miasik** [comment] 2022-04-14 16:23
Interesting, I'm not sure how I missed this. Thanks for bringing this to my attention. 

I have managed to reproduce the issue on my end. I think I know what the cause of this is. Seems to be a bug I introduced when implementing the Android port. I'll take a look at this and try to create a new release ASAP since this is likely affecting a lot of users. (I noticed a UWP review about this as well)

Thanks again for reporting this, much appreciated. 👍 
I'll report back once I have something concrete.

**Comment by adrian-miasik** [comment] 2022-04-14 16:45
I'm going to do a bit of testing on devices but I've drafted up a PR (#72) explaining the bug a bit more. Once that's merged in I'll create a hotfix release for this concern which should solve your issue.

**Closed** 2022-04-14 17:00 UTC
Labels: 3. Priority: Urgent

**Comment by fortisconsulting** [comment] 2022-04-14 17:17
Hi Adrian,

Thanks for your quick response!

Sorry to ask a rookie question: how do I get access to version 2.1.1?  My PC desktop app is still on 2.1.0 and when I download and reinstall from the Microsoft Store, it's still the old one.

Best,
Eric Teachout, CSM
Owner & Project Manager

Fortis Agilis Consulting
Courage & Agility for Your Strategic Initiatives

Project Management  |  Digital Marketing  |  E-Learning & Communications

On 4/14/2022 12:01:09 PM, Adrian Miasik ***@***.***> wrote:

Closed #71<https://github.com/adrian-miasik/unity-pomodoro/issues/71> via #72<https://github.com/adrian-miasik/unity-pomodoro/pull/72>.

**Comment by adrian-miasik** [comment] 2022-04-14 17:39
Hello Eric,

Haha, no worries!
Happy to answer that for you.

The latest version is currently building, once those are ready I'll be creating a new release with the new builds/binaries. I've drafted a release but am waiting on the builds to finish before going live. Once everything is ready on my end, you should see a new release in the releases page on this repository.

You can keep an eye on the releases page, or get a notification for releases from GitHub by watching this repo (Top left of repo site: Watch > Custom > Check 'Releases' > Press Apply)

![image](https://user-images.githubusercontent.com/12757380/163442253-68e1e57c-670e-4f14-8d94-c84d03f9f6c5.png)

If you are a UWP (Microsoft Store) user, the store should prompt or update the app. You can alternatively fetch the latest updates there by going to Library and pressing the 'Get Update' button. One thing to note is that there is a certification process here and an additional pipeline process, so this takes a bit more time to update.

![image](https://user-images.githubusercontent.com/12757380/163442984-a6747f2e-9f42-41a4-85be-08547725614b.png)

**The fastest way to get this build is to keep an eye out for the releases tab on the GitHub page here: https://github.com/adrian-miasik/unity-pomodoro/releases**

**Comment by adrian-miasik** [comment] 2022-04-14 17:41
The fastest way to get this build is to keep an eye out for the releases tab on the GitHub page here: https://github.com/adrian-miasik/unity-pomodoro/releases

**Comment by adrian-miasik** [comment] 2022-04-14 17:43
![image](https://user-images.githubusercontent.com/12757380/163444224-4e191c7e-8e35-4271-a145-d196c260bde1.png)

**Comment by adrian-miasik** [comment] 2022-04-14 17:51
Ah just saw you were a Microsoft store user. I say check back either tomorrow or the day after to get the 2.1.1 release.

**Comment by fortisconsulting** [comment] 2022-04-14 19:14
Thank you!

- Eric

On 4/14/2022 12:51:48 PM, Adrian Miasik ***@***.***> wrote:

Ah just saw you were a Microsoft store user. I say check back either tomorrow or the day after to get the 2.1.1 release.

**Comment by adrian-miasik** [comment] 2022-04-15 00:45
Hey Eric, 

Last message. I don't want to spam you with too many notifications.
But the new version seems to be up on the Microsoft store now. :)

**Comment by fortisconsulting** [comment] 2022-04-18 23:02
Thanks so much, Adrian!  It did auto-update for me through the Microsoft Store.

This was a great help!  I was going crazy without the timer!

Eric Teachout, CSM
Owner & Project Manager

Fortis Agilis Consulting
Courage & Agility for Your Strategic Initiatives

Project Management  |  Digital Marketing  |  E-Learning & Communications
Schedule a Meeting with Me<https://calendly.com/fortisagilis>

On 4/14/2022 7:46:03 PM, Adrian Miasik ***@***.***> wrote:

Hey Eric,

Last message. I don't want to spam you with too many notifications.
But the new version seems to be up on the Microsoft store now. :)
